# .github/workflows/deploy.yml
name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: live-chat-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Deploy to DigitalOcean Droplet
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
        DROPLET_IP: ${{ vars.DROPLET_IP }}
        USER: deploy
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key -r ./* $USER@$DROPLET_IP:/home/deploy/github/live-chat
        ssh -i private_key $USER@$DROPLET_IP 'cd /home/deploy/github/live-chat/backend && npm install && pm2 restart all'
